### ISSUE TITLE
lint check Warning,but can't commit

### ISSUE THREAD

**Issue by HellerSam** [skateboard1991/hecatoncheires#1]
Issues see title,
errmsg:
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/51/yfj55v311x35c8hxx8cfm1gm0000gn/T/SourceTreeTemp.luvWHB 
start pmd check
start lint check
Parallel execution is an incubating feature. > Configure project :feedback pom config [groupId:me.ele.lpd.baidu, artifactId:crowd_feedback, version:0.3.8] lpd moudle plugin apply.. > Configure project :app WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html lpd moudle plugin apply.. > Task :feedback:preBuild UP-TO-DATE > Task :libzxing:preBuild UP-TO-DATE > Task :feedback:preDebugBuild UP-TO-DATE > Task :libzxing:preDebugBuild UP-TO-DATE > Task :app:prepareLintJar UP-TO-DATE > Task :app:preBuild UP-TO-DATE > Task :feedback:checkDebugManifest UP-TO-DATE > Task :libzxing:checkDebugManifest UP-TO-DATE > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE > Task :app:mainApkListPersistenceDebug UP-TO-DATE > Task :feedback:processDebugManifest UP-TO-DATE > Task :libzxing:processDebugManifest UP-TO-DATE > Task :feedback:preQaBuild UP-TO-DATE > Task :libzxing:preQaBuild UP-TO-DATE > Task :app:extractProguardFiles UP-TO-DATE > Task :feedback:checkQaManifest UP-TO-DATE > Task :libzxing:checkQaManifest UP-TO-DATE > Task :feedback:processQaManifest UP-TO-DATE > Task :libzxing:processQaManifest UP-TO-DATE > Task :feedback:preReleaseBuild UP-TO-DATE > Task :libzxing:preReleaseBuild UP-TO-DATE > Task :feedback:checkReleaseManifest UP-TO-DATE > Task :libzxing:checkReleaseManifest UP-TO-DATE > Task :feedback:processReleaseManifest UP-TO-DATE > Task :libzxing:processReleaseManifest UP-TO-DATE > Task :feedback:prepareLintJar UP-TO-DATE > Task :libzxing:prepareLintJar UP-TO-DATE > Task :app:preDebugBuild UP-TO-DATE > Task :app:checkDebugManifest UP-TO-DATE > Task :app:processDebugManifest UP-TO-DATE > Task :app:preQaBuild UP-TO-DATE > Task :app:checkQaManifest UP-TO-DATE > Task :app:createQaCompatibleScreenManifests UP-TO-DATE > Task :app:mainApkListPersistenceQa UP-TO-DATE > Task :app:processQaManifest UP-TO-DATE > Task :app:preReleaseBuild UP-TO-DATE > Task :app:checkReleaseManifest UP-TO-DATE > Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE > Task :app:mainApkListPersistenceRelease UP-TO-DATE > Task :app:processReleaseManifest UP-TO-DATE > Task :app:incrementlint Ran lint on variant qa: 76 issues found Ran lint on variant release: 78 issues found Ran lint on variant debug: 78 issues found Wrote HTML report to file:///Users/sam/work_waimai/work_space/Crowdsource-android/app/build/reports/lint-results.html Wrote XML report to file:///Users/sam/work_waimai/work_space/Crowdsource-android/app/build/reports/lint-results.xml BUILD SUCCESSFUL in 1m 7s 32 actionable tasks: 1 executed, 31 up-to-date
Completed with errors, see above

**Comment by skateboard1991** [comment]
I have fixed this bug.Please update version to 1.0.1
